### PR TITLE
Fix IE Browser issues and improve UX while connecting to survey

### PR DESCRIPTION
**Pull request by tertek**
Some of our participants could not login because IE does not support arrow functions which resulted in syntax error.
Also the ClipBoardData API seems broken on IE which has been fixed with IE detection.

Additionally I have improved the user experience while connecting to the survey after a successful access code submission.

### CODE REVIEW

**Comment by tertek** [comment]
@123andy could you have a quick look on this please? We have just sent out 40k invitations and the amount of IE users who cannot login is increasing....

**Review by 123andy — APPROVED** [review]

**Comment by 123andy** [comment]
Just merged and released an update to Vanderbitlt (v1.1.5)

thx,

-A

________________________________

**Comment by tertek** [comment]
Thank you for the quick response.

**Comment by 123andy** [comment]
Thanks for your PRs!  The product gets better if we all are patient enough to share feedback and get it incorporated into the repos...
________________________________

**Pull request merged**
